name       : ocl-icd
version    : 2.2.12
release    : 6
source     :
    - https://github.com/OCL-dev/ocl-icd/archive/v2.2.12.tar.gz : 17500e5788304eef5b52dbe784cec197bdae64e05eecf38317840d2d05484272
license    : BSD-2-Clause
component  : programming.library
summary    : Vendor Neutral OpenCL Implementation
description: |
    This package aims at creating an Open Source alternative to vendor specific OpenCL ICD loaders.
optimize   : speed
emul32     : yes
builddeps  :
    - opencl-headers
    - ruby
rundeps    :
    - devel : opencl-headers
setup      : |
    %reconfigure --disable-static \
               --enable-custom-vendordir=/usr/share/OpenCL/vendors
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

