name       : ocl-icd
version    : 2.2.14
release    : 9
source     :
    - https://github.com/OCL-dev/ocl-icd/archive/refs/tags/v2.2.14.tar.gz : 46df23608605ad548e80b11f4ba0e590cef6397a079d2f19adf707a7c2fbfe1b
license    : BSD-2-Clause
component  : programming.library
homepage   : https://github.com/OCL-dev/ocl-icd/
summary    : Vendor Neutral OpenCL Implementation
description: |
    This package aims at creating an Open Source and vendor-neutral alternative to vendor specific OpenCL ICD loaders.
optimize   : speed
emul32     : yes
builddeps  :
    - opencl-headers
    - ruby
rundeps    :
    - devel : opencl-headers
setup      : |
    %reconfigure \
        --disable-static \
        --enable-custom-vendordir=/usr/share/OpenCL/vendors
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
