name       : ocl-icd
version    : 2.3.1
release    : 10
source     :
    - https://github.com/OCL-dev/ocl-icd/archive/refs/tags/v2.3.1.tar.gz : a32b67c2d52ffbaf490be9fc18b46428ab807ab11eff7664d7ff75e06cfafd6d
license    : BSD-2-Clause
component  : programming.library
homepage   : https://github.com/OCL-dev/ocl-icd/
summary    : Vendor Neutral OpenCL Implementation
description: |
    This package aims at creating an Open Source and vendor-neutral alternative to vendor specific OpenCL ICD loaders.
optimize   : speed
emul32     : yes
builddeps  :
    - opencl-headers
    - ruby
rundeps    :
    - devel : opencl-headers
setup      : |
    %reconfigure \
        --disable-static \
        --enable-custom-vendordir=/usr/share/OpenCL/vendors
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
