name       : ocl-icd
version    : 2.2.9
release    : 1
source     :
    - https://github.com/OCL-dev/ocl-icd/archive/v2.2.9.tar.gz : 88da749bc2bd75149f0bb6e72eb4a9d74401a54f4508bc730f13cc03c57a17ed
license    : BSD-2-Clause
component  : programming.library
summary    : Vendor Neutral OpenCL Implementation
description: |
    This package aims at creating an Open Source alternative to vendor specific OpenCL ICD loaders.
optimize   : speed
builddeps  :
    - ruby
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-implementation-for-OpenCL-provider-i.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
